apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: my-fortune
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        image: quay.io/rhn_support_ekasprzy/fortune:3
        ports:
        - containerPort: 8080
